libuv: Autospec creation for update from version 1.43.0 to version 1.44.0
Ben Noordhuis (12):
      darwin: remove EPROTOTYPE error workaround (#3405)
      darwin: translate EPROTOTYPE to ECONNRESET (#3413)
      android: use libc getifaddrs() (#3412)
      unix: don't allow too small thread stack size (#3423)
      bsd: ensure mutex is initialized (#3428)
      test: remove flaky test ipc_closed_handle (#3464)
      darwin: bump minimum supported version to 10.15 (#3406)
      doc: clarify android api level (#3480)
      test: fix ipc_send_recv_pipe flakiness (#3478)
      unix,win: add uv_available_parallelism() (#3499)
      zos: fix build breakage (#3513)
      unix: simplify uv__cloexec_fcntl() (#3492)

Darshan Sen (1):
      win,errors: remap ERROR_ACCESS_DENIED to UV_EACCES (#3193)

David Carlier (1):
      freebsd: use copy_file_range() in uv_fs_sendfile() (#3496)

David Machaj (1):
      win: replace CRITICAL_SECTION+Semaphore with SRWLock (#3383)

Guilherme Íscaro (1):
      test: use closefd in runner-unix.c (#3497)

Jameson Nash (15):
      build: fix cmake install locations (#3415)
      build: rename CFLAGS to AM_CFLAGS (#3431)
      process,bsd: handle kevent NOTE_EXIT failure (#3451)
      loop: add pending work to loop-alive check (#3466)
      win: use GetTickCount64 for uptime again (#3470)
      win,fs: avoid closing an invalid handle (#3473)
      fix oopsie from #3466 (#3475)
      win: fix style nits [NFC] (#3474)
      core: change uv_get_password uid/gid to unsigned (#3476)
      Reland "macos: use posix_spawn instead of fork" (#3257)
      process: remove OpenBSD from kevent list (#3506)
      process: only use F_DUPFD_CLOEXEC if it is defined (#3512)
      doc: add secondary GPG ID for vtjnash
      unix: remove uv__cloexec_ioctl() (#3515)
      2022.03.07, Version 1.44.0 (Stable)

Jeremy Rose (1):
      process: monitor for exit with kqueue on BSDs (#3441)

Jessica Clarke (1):
      unix: fix STATIC_ASSERT to check what it means to check (#3417)

Luca Adrian L (1):
      win: return fractional seconds in uv_uptime() (#3455)

Momtchil Momtchev (3):
      test: fix flaky uv_fs_lutime test (#3424)
      bench: add `uv_queue_work` ping-pong measurement (#3425)
      win,fs: consider broken pipe error a normal EOF (#3053)

Ondřej Surý (2):
      unix: ensure struct msghdr is zeroed in recvmmsg (#3419)
      test: test with maximum recvmmsg buffer (#3419)

Paul Evans (1):
      document the values of enum uv_stdio_flags (#3039)

Ryan Liptak (1):
      test: fix benchmark-ping-udp (#2817)

Santiago Gimeno (1):
      test: fix flaky udp_mmsg test

UMU (1):
      build: fix error C4146 on MSVC (#3271)

Vittore F. Scolari (1):
      hurd: unbreak build on GNU/Hurd (#3450)

WenTao Ou (1):
      build: export uv_a for cmake (#3373)

cjihrig (3):
      Add SHA to ChangeLog
      Now working on version 1.43.1
      doc: fix v1.43.0 changelog entries

gengjiawen (1):
      doc: add gengjiawen as maintainer (#3430)

jonilaitinen (1):
      win: restrict system DLL load paths (#3395)

roflcopter4 (1):
      win,poll: add the MSAFD GUID for AF_UNIX (#3511)

ssrlive (2):
      thread,win: fix C90 style nit (#3393)
      android: fix build error when no ifaddrs.h (#3505)

twosee (1):
      win,loop: add missing uv_update_time (#3175)

woclass (1):
      doc/guide: update content and sample code (#3408)

wyckster (1):
      doc: checkout -> check out (#3489)