libuv: Autospec creation for update from version 1.48.0 to version 1.49.0
Abdirahim Musse (1):
      test: pipe_overlong_path handle ENAMETOOLONG

Andy Pan (12):
      sunos: sync tcp keep-alive with other unices (#4337)
      dragonfly: disable SO_REUSEPORT for UDP socket bindings (#4410)
      test: remove the obsolete HAVE_KQUEUE macro
      unix: use the presence of SOCK_* instead of OS macros for socketpair
      bsd: support pipe2() on *BSD (#4412)
      unix: support SO_REUSEPORT with load balancing for TCP
      test: fix the flaky test-tcp-reuseport
      unix: support SO_REUSEPORT with load balancing for UDP (#4419)
      tcpkeepalive: distinguish OS versions and use proper time units
      linux: eliminate a read on eventfd per wakeup (#4400)
      kqueue: use EVFILT_USER for async if available
      kqueue: disallow ill-suited file descriptor kinds (#4513)

Anthony Alayo (1):
      build: add alias for libuv to CMakeLists.txt (#4297)

Ben Noordhuis (22):
      test: fix -Wpointer-to-int-cast on 32 bits systems (#4309)
      linux: create io_uring sqpoll ring lazily (#4315)
      test: disable env var test under win32+asan (#4342)
      test,ci: fix [AM]San, disable ASLR (#4365)
      win: remove _alloca usage (#4361)
      unix: reinstate preadv/pwritev fallback code (#4345)
      linux: don't delay EPOLL_CTL_DEL operations (#4328)
      doc: correct udp socket options documentation (#4371)
      linux: don't use sendmmsg() for single datagrams (#4366)
      unix: fix fd leaks in SCM_RIGHTS error path (#4358)
      win: robustify uv_os_getenv() error checking (#4339)
      test: use newer ASSERT_MEM_EQ macro (#4346)
      build: fix android ci build (#4451)
      unix,win: export wtf8 functions properly (#4437)
      test: handle zero-length udp datagram (#4344)
      test,openbsd: remove superfluous ifdef guard (#4461)
      linux: support abstract unix socket autobinding (#4499)
      win: compute parallelism from process cpu affinity (#4521)
      win: fix uv_available_parallelism on win32 (#4525)
      unix: restore tty attributes on handle close (#4399)
      test: delete test with invalid assumption (#4530)
      unix: work around arm-linux-gnueabihf-gcc bug (#4537)

Brad King (1):
      unix: de-duplicate conditions for using kqueue (#4378)

Edigleysson Silva (Edy) (1):
      test: run android tests on ci (#4517)

Farzin Monsef (2):
      cygwin: implement uv_resident_set_memory (#4333)
      linux: fix /proc/self/stat executable name parsing (#4353)

Geddy (1):
      udp,unix: fix sendmsg use-after-free (#4321)

Hüseyin Açacak (3):
      win: map ERROR_BAD_EXE_FORMAT to UV_EFTYPE (#4445)
      win: fix env var in uv_os_homedir and uv_os_tmpdir (#4464)
      win,fs: use the new Windows fast stat API (#4327)

Ian Butterworth (1):
      win,fs: use posix delete semantics, if supported (#4318)

Jameson Nash (8):
      misc: run sample CI when code changes (#4324)
      Create dependabot.yml for updating github-actions (#4450)
      win,error: remap ERROR_NO_DATA to EAGAIN (#4471)
      win,pipe: fix race with concurrent readers (#4470)
      win,signal: fix data race dispatching SIGWINCH (#4488)
      win,pipe: restore fallback handling for blocking pipes (#4511)
      win,pipe: fix missing assignment to success (#4515)
      win,pipe: fix another missing assignment to success (#4523)

Jeffrey H. Johnson (2):
      aix,ibmi: fix compilation errors in fs_copyfile (#4404)
      dragonflybsd: fix compilation failure (#4534)

Juan José Arboleda (2):
      linux,darwin: make `uv_fs_copyfile` behaves like `cp -r` (#4396)
      doc: add entries for extended getpw

Matheus Izvekov (2):
      build: ubsan fixes (#4254)
      win: fix fs.c ubsan failure (#4491)

Olivier Valentin (2):
      hurd: add includes and macro prerequisites
      hurd: stub uv_thread_setpriority()

Ondřej Surý (1):
      unix: expand uv_available_parallelism() to support more platforms

Raihaan Shouhell (1):
      darwin: add udp mmsg support (#4527)

Richard Lau (2):
      test: rmdir can return `EEXIST` or `ENOTEMPTY`
      test: check for `UV_CHANGE` or `UV_RENAME` event

Santiago Gimeno (9):
      Add SHA to ChangeLog
      Now working on version 1.48.1
      win: almost fix race detecting ESRCH in uv_kill (#4341)
      fsevents: detect watched directory removal (#4376)
      linux: disable SQPOLL io_uring by default (#4492)
      unix,fs: silence -Wunused-result warning (#4496)
      doc: document specific macOS fs_event behavior (#4503)
      doc: add known issue in armv7 (#4541)
      2024.09.25, Version 1.49.0 (Stable)

Saúl Ibarra Corretgé (7):
      unix,fs: fix realpath calls that use the system allocator
      unix,win: error on zero delay tcp keepalive
      win: simplify uv_once implementation
      darwin: simplify uv_hrtime
      mailmap: update saghul's main email address
      win: remove no longer needed define
      ci: use macOS 12 for macOS and iOS builds

Shelley Vohr (1):
      win: remove deprecated GetVersionExW call (#4486)

Thomas Walter (1):
      linux: fix uv_available_parallelism using cgroup  (#4278)

Uilian Ries (1):
      doc: add instruction how to install with Conan (#4432)

Viacheslav Muravyev (3):
      unix,win: remove unused req parameter from macros (#4435)
      misc: remove splay trees macros (#4469)
      unix,win: remove unused rb-tree macro parameters (#4518)

Zuohui Yang (1):
      win: use NtQueryInformationProcess in uv_os_getppid (#4514)

dependabot[bot] (4):
      ci: bump upload and download-artifact versions (#4473)
      ci: bump actions/setup-python from 4 to 5 (#4475)
      ci: bump KyleMayes/install-llvm-action from 1 to 2 (#4472)
      ci: bump actions/checkout to 4 (#4474)

hiiizxf (1):
      doc: fix tty example segfault (#4322)

josedelinux (1):
      doc: fix some typos

tgolang (1):
      doc: fix typos in ChangeLog (#4355)

zeertzjq (1):
      doc: correct names of Win32 APIs in fs.rst (#4408)

握猫猫 (3):
      doc: document uv_loop_option
      doc: fix the `uv_*_set_data` series of functions
      doc: properly label enumerations and types (#4506)

郑苏波 (Super Zheng) (1):
      darwin: fix crash on iOS(arm64)