libuv: Autospec creation for update from version 1.38.1 to version 1.39.0
Bartosz Sosnowski (1):
      tcp: fail instantly if local port is unbound

Ben Noordhuis (3):
      unix: use relaxed loads/stores for clock id
      test: fix thread race in process_title_threadsafe
      unix: don't use _POSIX_PATH_MAX

Carter Li (1):
      linux: use copy_file_range for uv_fs_copyfile when possible

Evan Lucas (1):
      darwin: use IOKit for uv_cpu_info

George Zhao (1):
      build,win: link to user32.lib and advapi32.lib

Jameson Nash (4):
      win,fs: avoid implicit access to _doserrno
      test: give hrtime test a custom 20s timeout
      doc: fix most sphinx warnings
      nfci: address some style nits

Juan Sebastian velez Posada (1):
      docs: improve the descriptions for get memory info

Michael Penick (1):
      win,tcp: avoid reinserting a pending request (#2688)

Mustafa M (1):
      win,fs: use CreateDirectoryW instead of _wmkdir

OleksandrKvl (1):
      unix,stream: clear read/write states on close/eof

Richard Lau (1):
      aix: protect uv_exepath() from uv_set_process_title()

Ryan Liptak (3):
      test: add udp-mmsg test
      udp: add uv_udp_using_recvmmsg query
      unix: error when uv_setup_args() is not called

TK-one (1):
      doc: add more error constants

Trevor Norris (3):
      zos: fix potential event loop stall
      include: add internal fields struct to uv_loop_t
      core: add API to measure event loop idle time

Turbinya (1):
      include: fx c++ style comments warnings

cjihrig (5):
      Add SHA to ChangeLog
      Now working on version 1.38.2
      unix: handle src, dest same in uv_fs_copyfile()
      Revert "unix,stream: clear read/write states on close/eof"
      2020.08.26, Version 1.39.0 (Stable)

erw7 (1):
      build,cmake: Change installation location on MinGW

escherstair (5):
      win,nfc: fix integer comparison signedness
      win,nfc: use #pragma warnings() for MSVC only
      win,nfc: removed some unused variables
      win,nfc: add missing return statement
      win,nfc: disable clang-format for #include order

gengjiawen (1):
      build: add more failed test, for qemu version bump

ssrlive (1):
      unix: squelch harmless valgrind warning

tjarlama (2):
      fs: clobber req->path on uv_fs_mkstemp() error
      test: avoid double evaluation in ASSERT_BASE macro

司徒玟琅 (1):
      cmake: fix compile error C2001 on Chinese Windows